### ISSUE TITLE
Displaying of Partially open license

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#34]
1. The data with this license should display some coordinates, but this must be limited to 1 decimal place (eg. 41.9; 19.4), which approximates to the precision of about 11 km. Currently it displays N/A in both view and export.
2. The data about exact date of record should also be hidden. I think we can stick only to the year of observation.

**Comment by nikazooz** [comment]
@gpopac Should the displayed accuracy be changed as well?

**Comment by gpopac** [comment]
@nikazooz Yes, good point! Also in exported data, the precision should be changed to 11100 m.

**Comment by nikazooz** [comment]
We use radius for accuracy, so it would be half of it

**Comment by gpopac** [comment]
@nikazooz 
Phone GPS returns the radius of 68% confidence.
With note that longitude is more precise in our region (than this general data from equator), maybe we can settle on 5000 m value?.
