### ISSUE TITLE
Biologer.org does not display pictures in All field observations

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#35]
As the editor for Lepidoptera I can see all the pictures in „Administrator > All field observations“ from Lepidoptera group. However, the picture is not displayed if I click on any other group (i.e. could not see Coleoptera or Birds). The software should display images according to image licenses, not according to editor rights.
![screenshot](https://user-images.githubusercontent.com/21208434/131214735-f2b74536-ba24-41c4-8121-6cf9269201be.png)

Note this only happens on Serbian Biologer, probably due to Linode hosting of images.

**Comment by nikazooz** [comment]
@gpopac Cannot reproduce this. Is it still an issue?

**Comment by gpopac** [comment]
@nikazooz no problems now, magically resolved on its own :)
