### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#44]
GDPR should be updated so that we are more precise towards the users. After some discussion, there is a final suggestion here:
[GDPR-final.docx](https://github.com/Biologer/Biologer/files/7368371/GDPR-final.docx)

**Comment by gpopac** [comment]
English text is rewritten according to Serbian. Serbian text is corrected.
[GDPR-final_v1.docx](https://github.com/Biologer/Biologer/files/7456880/GDPR-final_v1.docx)

**Comment by gpopac** [comment]
Updated Croatian translation.
[GDPR-final_v2.docx](https://github.com/Biologer/Biologer/files/7475655/GDPR-final_v2.docx)

**Comment by gpopac** [comment]
@nikazooz Da li možeš da staviš ovo online pošto dodajemo app na iOS app store, pa da imamo sveže zbog recenzije tamo?

**Comment by nvasic88** [comment]
rešeno
