### ISSUE TITLE
Higher taxnonomic categories are not visible to the editors

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#46]
Example: If user selects „Insects“ as a taxon, the editors for „Lepidoptera“ or „Coleoptera“ will not see this record.

Note: If we enable editors to see higher taxonomic rank, this would violate licence agreement for closed licences (since the editors could see the taxa from their own groups only).

**Comment by nikazooz** [comment]
Do you mean to allow seeing taxa of higher order than curated but not "sibling" taxa that are not curated by the user?

**Comment by gpopac** [comment]
@nikazooz Yes, exactly.
And rethinking licenses, if a user selects higher taxonomic rank this means that all lower taxa editors should be legal to access the data. I.e. If user selects "Animals“ any editor in Animals groups (including Lepidoptera, Reptilia, Coleoptera, etc.) should be able to view this record.

**Comment by nikazooz** [comment]
@gpopac This is done and deployed
