### ISSUE TITLE
API access and mail confirmed

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#47]
1. Currently, user is not able to access some APIs before email is confirmed. To simplify implementation in the applications we should enable users to access this APIs:
view-groups
taxa
observation-types
elevation

2. There should be a simple call to get response if email is confirmed. It could be implemented in my/profile API?

**Comment by nikazooz** [comment]
@nikazooz Why is elevation endpoint needed? To me it doesn't make sense for non-verified users to use it, similarly to how they should not be able to add observations.

**Comment by gpopac** [comment]
@nikazooz

**Comment by gpopac** [comment]
@nikazooz Implemented in Biologer for Android: https://github.com/Biologer/Biologer-Android/commit/776729f543c2574e330c31d3a9731ef6f1be54b1
