### ISSUE TITLE
User email address is visible within filters

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#51]
We have a security issue, since the email address is visible in filters when searching for user name. This should be fixed ASAP!

**Comment by nikazooz** [comment]
@gpopac In which filters?

**Comment by gpopac** [comment]
It appears in Observer. I.e. Pending observations > Filters > Observer. 
But note that email server to determine users having the same full name. We need to display some unique user identifier in this filter, or maybe to display part of email address? Such as... g****c@gmial.com.
