### ISSUE TITLE
Add supporting fundations

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#53]
Page https://biologer.org/pages/about/development-supporters should be updated with the info on our new supporters.

1. Support from BiH

Biologer community in Bosnia and Herzegovina and development of iOS application was supported by the Environmental Protection Fund of the Federation of Bosnia and Herzegovina through the project "Biologer – Online database about biodiversity of BiH“, realised by BIO.LOG society.
Биологер заједница у Босни и Херцеговини и развој iOS апликације су подржани од стране Фонда за заштиту околиша Федерације БиХ кроз пројекат „Биологер - онлајн база података о биодиверзитету БиХ“, реализован преко удружења BIO.LOG.

Links to be included in the text:
https://fzofbih.org.ba
http://www.biolog.ba/

![bio](https://user-images.githubusercontent.com/21208434/143659498-acd84f20-e201-422f-8400-8803a0955976.jpg)
![fond za zaštitu okolisa bih](https://user-images.githubusercontent.com/21208434/143658284-8b578512-dd83-4ddf-9b17-22b9184f127b.jpg)

2. Support from Serbia/Sweeden

Development of entire software platform was continued in the course of the project "Eco network for the future of Serbia", as part of ECO-SYSTEM program realised by Young Researchers of Serbia, and supported by Sweden.
Развој читаве софтверске платформе је настављен у оквиру пројекта „Еко мрежа за будућност Србије“, као део активности пограма ЕКО-СИСТЕМ који реализују Млади истраживачи Србије, а подржава Шветска.
Logo EKO-SISTEM, pa MIS, pa Švedska

Links to be included in the text: 
https://ekosistem.mis.org.rs/
https://www.mis.org.rs
https://www.swedenabroad.se/en/

![EcoSystem-Logo-ENG-01](https://user-images.githubusercontent.com/21208434/143658846-cf60b995-fc1f-46e6-b1ae-dc07c55f2bea.png)
![MIS-Logo-01](https://user-images.githubusercontent.com/21208434/143658868-64eff783-c7d8-4676-9849-f996cb22b4be.png)

![MIS cir color](https://user-images.githubusercontent.com/21208434/143658894-8fd30ad4-b9da-44ba-9cd5-d07e4bd00ce0.png)
![MIS lat color](https://user-images.githubusercontent.com/21208434/143658895-23198dc2-22e3-4355-8a37-03541c1aaf8e.png)
![MIS eng color](https://user-images.githubusercontent.com/21208434/143658898-569013ea-bf6f-45a3-a481-1dbfbb2249fa.png)

![Sweden_logotype_Serbia](https://user-images.githubusercontent.com/21208434/143658912-b96a8529-69e9-45f5-83fc-92eef91dba20.png)
![Švedska_latinica](https://user-images.githubusercontent.com/21208434/143658919-9c2fc7ad-b470-4cd7-a960-f38dad48b8b0.png)

**Comment by gpopac** [comment]
++++++

U odeljak o pojedincima treba dodati:

1. Nikola Popović – development of iOS application.
2. Nikola Vasić – developement of taxonomic database and BirdLoger.

**Comment by gpopac** [comment]
Deo teksta gde se pominje moje finansiranje kroz Ministarstvo treba dopuniti sa još dva broja projekta:
451-03-68/2020-14/200124
451-03-9/2021-14/200124

**Comment by nikazooz** [comment]
@gpopac Jesu li i ti tvoji projekti preko Departmana za biologiju i ekologiju PMF-a u Nišu?

**Comment by nikazooz** [comment]
Done

**Comment by gpopac** [comment]
@nikazooz Super je ovako i dobro si dodao projekte. Poslao sam i ostalima da pogledaju, ali se nadam da neće biti zamerki.

**Comment by gpopac** [comment]
@nikazooz moram opet da otvorim bug, pošto treba da ispravimo dve sitnice.
1. Logo projekta ekosistemi treba da bude sa rečenicom ispod.
2. Veličina slika na toj stranici je prevelika. To je nešto što sam i ja primetio ranije ali nisam hteo da te gnjavim previše. Mislim da bi bilo dobro da se svi logoi smanje malo na neku razumnu veličinu.

**Comment by gpopac** [comment]
![EcoSystem-LogoFull-ENG-01](https://user-images.githubusercontent.com/21208434/148660860-504b02a5-238d-4f99-b1b2-268953bda1ca.png)
![Uploading MIS-LogoFull-01.png…]()

**Comment by gpopac** [comment]
![MIS-LogoFull-01](https://user-images.githubusercontent.com/21208434/148660872-eb5f3ab2-18d9-4409-945a-e2d0a7ef5460.png)

**Comment by nikazooz** [comment]
Sređeno
