### ISSUE TITLE
Biologer does not apply filters on Export of Literature data

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#60]
How to reproduce:
1. Open FIlters in Literature Observations; select Papilionoidea in the taxon field; check „Include lower taxa“; "Apply"
2. Actions > Export; Check „Apply filters“
3. All data from the database is exported disregarding the filters.

**Comment by nikazooz** [comment]
Fixed with [ab619e2a9ef3e8d0a2c597785e4c9d05f55f4ad0](https://github.com/Biologer/Biologer/commit/ab619e2a9ef3e8d0a2c597785e4c9d05f55f4ad0)
