### ISSUE TITLE
Move biologer.org to a new webpage

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#68]
http://185.22.145.23:81 should point to a domain biologer.org.

**Comment by gpopac** [comment]
PS. Da li je potrebno da domen Biologer.org prenesemo na DZPPS ili mislite da je OK da ostane u mom vlasništvu?

**Comment by nikazooz** [comment]
> PS. Da li je potrebno da domen Biologer.org prenesemo na DZPPS ili mislite da je OK da ostane u mom vlasništvu?

Meni je potpuno svejedno.

> http://185.22.145.23:81 should point to a domain biologer.org.

Ako ćemo da biologer.org pokazuje na taj IP i imamo funcionalan sajt trebalo bi koristiti port 80 koji browser-i koriste podrazumevano

**Comment by gpopac** [comment]
@nikazooz Sada smo na portu 80.

Meni je najzgodnije da ne menjamo ništa što ne mora. Samo znam da nas neki antivirus programi proganjaju jer imamo org domen a vodi se na mene. Kontam da nije tako zanišljen biznis sa org domenima :D
