### ISSUE TITLE
Some uploaded photos from phone are not showing

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#72]
For example ID: 204672 and 204558. I will check if there are some errors in Android app, but this could be related to server using too much disk space?

EDIT! Now there are photos for mentioned IDs. But it took some time to generate them, thus it must be some server/biologer web app lag?

**Comment by nikazooz** [comment]
Image processing is relatively slow. If many images are uploaded at once from the phone it will take time for all of them to be processed.

**Comment by gpopac** [comment]
Images from the phone are already preprocessed to the appropriate size and small, thus thia is strange. Even if server does some processing it shoulb be quick on such a small image.

**Comment by nikazooz** [comment]
I've found something suboptimal in image processing (multiple unneeded reads and writes to Linode, which is not fast) and will fix it.

**Comment by nikazooz** [comment]
Should be a bit better now

**Comment by nikazooz** [comment]
Closing this. Feel free to open it if the issue persists
