### ISSUE TITLE
Google Search engine dows not find biologe.rs in search results

### ISSUE THREAD

**Issue by gpopac** [Biologer/Biologer#93]
Biologer.org was among the top rated web pages, but when we switched to biologer.rs we are not present in google at al! Any ideas on this? What’s wrong?

**Comment by nikazooz** [comment]
![Screenshot from 2022-11-24 13-51-14](https://user-images.githubusercontent.com/13997617/203788984-40ecdb11-fde2-4e4a-9fb7-99bd5d39bb97.png)

I don't see any problems

**Comment by gpopac** [comment]
Yes, it is fine for Biologer, but try searching Papilio machaon or lastin repak. Or any other species.
